import React, { useEffect } from 'react';
import dynamic from 'next/dynamic';
const LogoScreen = dynamic(() => import('../components/LogoScreen'), {
  ssr: false,
});
// import LogoScreen from '../components/LogoScreen'
import Head from 'next/head';
import getPlat from '../redux/actions/GetPlat';
import { useDispatch, useSelector } from 'react-redux';
import { useRouter } from 'next/router';

export default function Home() {
  const dispatch = useDispatch();

  const { userPlatfrom } = useSelector((state) => state.get_plat);

  useEffect(() => {
    // function to dispatch get platform api.
    const getPlatApi = async () => {
      dispatch(getPlat());
      // console.log(process.env.NEXT_PUBLIC_TEST_AWS_BUCKET, "env file");
    };
    // getPlatApi function call.
    getPlatApi();
    return () => {};
  }, []);

  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" type="image/x-icon" href="/assets/logo/logo.png"></link> */}
      </Head>
      <LogoScreen />
    </div>
  );
}
